module.exports = {
    NULL_VALUE: "필요한 값이 없습니다",
    OUT_OF_VALUE: "파라미터 값이 잘못되었습니다",
    ALREADY_USER: "이미 있는 id 입니다.",
    SIGNUP_SUCCESS : "회원가입 성공했습니다.",
    ID_OR_PW_WRO_VALUE: "아이디/비밀번호 값이 잘못됬습니다.",
    CREATED_TABLE_SUCCESS: "게시물 등록 성공",
    CREATED_TABLE_FAIL: "게시물 등록 실패",
    DELETE_TABLE_SUCCESS: "게시물 삭제 성공",
    DELETE_TABLE_FAIL: "게시물 삭제 실패",
    MODIFY_TABLE_SUCCESS: "게시물 수정 성공",
    MODIFY_TABLE_FAIL: "게시물 수정 실패",
    SEARCH_TABLE_SUCCESS: "게시물 조회 성공",
    SEARCH_TABLE_FAIL: "게시물 조회 실패",
    ALREADY_TABLE: "이미 있는 게시물 ID 입니다.",
    NO_TABLE: "존재하지 않는 게시물 입니다.",
    LOGIN_SUCCESS: "로그인 성공",
    DB_ERR: "데이터베이스 내부 에러",
    WRONG_TABLE_PW : "게시물 비밀번호가 일치하지 않습니다."
};